// flow-typed signature: 8767254b6c6879a0d4db4954c6a6ed7c
// flow-typed version: <<STUB>>/feathers-configuration_v^0.4.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-configuration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-configuration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-configuration/example/app' {
  declare module.exports: any;
}

declare module 'feathers-configuration/example/index' {
  declare module.exports: any;
}

declare module 'feathers-configuration/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-configuration/example/app.js' {
  declare module.exports: $Exports<'feathers-configuration/example/app'>;
}
declare module 'feathers-configuration/example/index.js' {
  declare module.exports: $Exports<'feathers-configuration/example/index'>;
}
declare module 'feathers-configuration/lib/index.js' {
  declare module.exports: $Exports<'feathers-configuration/lib/index'>;
}
