// flow-typed signature: 04695c4ac7ad292ad8fbc01859ab6e85
// flow-typed version: <<STUB>>/feathers-rest_v^1.7.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-rest/client' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/client/axios' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/client/base' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/client/fetch' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/client/index' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/client/jquery' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/client/request' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/client/superagent' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/index' {
  declare module.exports: any;
}

declare module 'feathers-rest/lib/wrappers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-rest/client.js' {
  declare module.exports: $Exports<'feathers-rest/client'>;
}
declare module 'feathers-rest/lib/client/axios.js' {
  declare module.exports: $Exports<'feathers-rest/lib/client/axios'>;
}
declare module 'feathers-rest/lib/client/base.js' {
  declare module.exports: $Exports<'feathers-rest/lib/client/base'>;
}
declare module 'feathers-rest/lib/client/fetch.js' {
  declare module.exports: $Exports<'feathers-rest/lib/client/fetch'>;
}
declare module 'feathers-rest/lib/client/index.js' {
  declare module.exports: $Exports<'feathers-rest/lib/client/index'>;
}
declare module 'feathers-rest/lib/client/jquery.js' {
  declare module.exports: $Exports<'feathers-rest/lib/client/jquery'>;
}
declare module 'feathers-rest/lib/client/request.js' {
  declare module.exports: $Exports<'feathers-rest/lib/client/request'>;
}
declare module 'feathers-rest/lib/client/superagent.js' {
  declare module.exports: $Exports<'feathers-rest/lib/client/superagent'>;
}
declare module 'feathers-rest/lib/index.js' {
  declare module.exports: $Exports<'feathers-rest/lib/index'>;
}
declare module 'feathers-rest/lib/wrappers.js' {
  declare module.exports: $Exports<'feathers-rest/lib/wrappers'>;
}
