// flow-typed signature: 36a80e0b52703afd94e90ef1d5c02404
// flow-typed version: <<STUB>>/feathers_v^2.1.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers/client' {
  declare module.exports: any;
}

declare module 'feathers/lib/application' {
  declare module.exports: any;
}

declare module 'feathers/lib/client/express' {
  declare module.exports: any;
}

declare module 'feathers/lib/client/index' {
  declare module.exports: any;
}

declare module 'feathers/lib/feathers' {
  declare module.exports: any;
}

declare module 'feathers/lib/index' {
  declare module.exports: any;
}

declare module 'feathers/lib/mixins/event' {
  declare module.exports: any;
}

declare module 'feathers/lib/mixins/index' {
  declare module.exports: any;
}

declare module 'feathers/lib/mixins/normalizer' {
  declare module.exports: any;
}

declare module 'feathers/lib/mixins/promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers/client.js' {
  declare module.exports: $Exports<'feathers/client'>;
}
declare module 'feathers/lib/application.js' {
  declare module.exports: $Exports<'feathers/lib/application'>;
}
declare module 'feathers/lib/client/express.js' {
  declare module.exports: $Exports<'feathers/lib/client/express'>;
}
declare module 'feathers/lib/client/index.js' {
  declare module.exports: $Exports<'feathers/lib/client/index'>;
}
declare module 'feathers/lib/feathers.js' {
  declare module.exports: $Exports<'feathers/lib/feathers'>;
}
declare module 'feathers/lib/index.js' {
  declare module.exports: $Exports<'feathers/lib/index'>;
}
declare module 'feathers/lib/mixins/event.js' {
  declare module.exports: $Exports<'feathers/lib/mixins/event'>;
}
declare module 'feathers/lib/mixins/index.js' {
  declare module.exports: $Exports<'feathers/lib/mixins/index'>;
}
declare module 'feathers/lib/mixins/normalizer.js' {
  declare module.exports: $Exports<'feathers/lib/mixins/normalizer'>;
}
declare module 'feathers/lib/mixins/promise.js' {
  declare module.exports: $Exports<'feathers/lib/mixins/promise'>;
}
