// flow-typed signature: 979989df7dc9ab4718222ae169c873ef
// flow-typed version: <<STUB>>/feathers-socketio_v^2.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-socketio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-socketio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-socketio/client' {
  declare module.exports: any;
}

declare module 'feathers-socketio/lib/client' {
  declare module.exports: any;
}

declare module 'feathers-socketio/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-socketio/client.js' {
  declare module.exports: $Exports<'feathers-socketio/client'>;
}
declare module 'feathers-socketio/lib/client.js' {
  declare module.exports: $Exports<'feathers-socketio/lib/client'>;
}
declare module 'feathers-socketio/lib/index.js' {
  declare module.exports: $Exports<'feathers-socketio/lib/index'>;
}
