// flow-typed signature: c9c5020624c6babf4ccf9ed0169c427e
// flow-typed version: <<STUB>>/feathers-errors_v^2.8.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-errors/handler' {
  declare module.exports: any;
}

declare module 'feathers-errors/lib/error-handler' {
  declare module.exports: any;
}

declare module 'feathers-errors/lib/index' {
  declare module.exports: any;
}

declare module 'feathers-errors/lib/not-found-handler' {
  declare module.exports: any;
}

declare module 'feathers-errors/not-found' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-errors/handler.js' {
  declare module.exports: $Exports<'feathers-errors/handler'>;
}
declare module 'feathers-errors/lib/error-handler.js' {
  declare module.exports: $Exports<'feathers-errors/lib/error-handler'>;
}
declare module 'feathers-errors/lib/index.js' {
  declare module.exports: $Exports<'feathers-errors/lib/index'>;
}
declare module 'feathers-errors/lib/not-found-handler.js' {
  declare module.exports: $Exports<'feathers-errors/lib/not-found-handler'>;
}
declare module 'feathers-errors/not-found.js' {
  declare module.exports: $Exports<'feathers-errors/not-found'>;
}
