// flow-typed signature: f50447f03d848bfdcef1df6cb77cb559
// flow-typed version: <<STUB>>/feathers-hooks_v^2.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-hooks/hooks' {
  declare module.exports: any;
}

declare module 'feathers-hooks/lib/commons' {
  declare module.exports: any;
}

declare module 'feathers-hooks/lib/hooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-hooks/hooks.js' {
  declare module.exports: $Exports<'feathers-hooks/hooks'>;
}
declare module 'feathers-hooks/lib/commons.js' {
  declare module.exports: $Exports<'feathers-hooks/lib/commons'>;
}
declare module 'feathers-hooks/lib/hooks.js' {
  declare module.exports: $Exports<'feathers-hooks/lib/hooks'>;
}
