// flow-typed signature: bb0bd23ae15f2cdbe81b454737a71713
// flow-typed version: <<STUB>>/feathers-hooks-common_v^3.5.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-hooks-common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-hooks-common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-hooks-common/lib/common/_conditionals' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/_pluck' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/_remove' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/_set-fields' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/_transform-items' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/_traverse' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/delete-by-dot' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/every' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/exists-by-dot' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/get-by-dot' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/iff-else' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/iff' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/is-not' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/set-by-dot' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/some' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/common/unless' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/filters/combine' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/filters/index' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/filters/pluck' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/filters/remove' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/filters/set-filtered-at' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/filters/traverse' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/index' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/permissions/combine' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/permissions/index' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/callback-to-promise' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/check-context-if' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/check-context' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/client' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/combine' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/de-populate' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/debug' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/disable-multi-item-change' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/disable' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/disallow' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/discard' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/get-items' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/index' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/is-provider' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/legacy-populate' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/lower-case' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/params-for-server' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/params-from-client' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/pluck-query' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/pluck' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/populate' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/prevent-changes' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/promise-to-callback' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/remove-query' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/remove' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/replace-items' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/serialize' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/set-created-at' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/set-now' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/set-slug' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/set-updated-at' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/sifter' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/soft-delete' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/stash-before' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/traverse' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/validate-schema' {
  declare module.exports: any;
}

declare module 'feathers-hooks-common/lib/services/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-hooks-common/lib/common/_conditionals.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/_conditionals'>;
}
declare module 'feathers-hooks-common/lib/common/_pluck.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/_pluck'>;
}
declare module 'feathers-hooks-common/lib/common/_remove.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/_remove'>;
}
declare module 'feathers-hooks-common/lib/common/_set-fields.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/_set-fields'>;
}
declare module 'feathers-hooks-common/lib/common/_transform-items.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/_transform-items'>;
}
declare module 'feathers-hooks-common/lib/common/_traverse.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/_traverse'>;
}
declare module 'feathers-hooks-common/lib/common/delete-by-dot.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/delete-by-dot'>;
}
declare module 'feathers-hooks-common/lib/common/every.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/every'>;
}
declare module 'feathers-hooks-common/lib/common/exists-by-dot.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/exists-by-dot'>;
}
declare module 'feathers-hooks-common/lib/common/get-by-dot.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/get-by-dot'>;
}
declare module 'feathers-hooks-common/lib/common/iff-else.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/iff-else'>;
}
declare module 'feathers-hooks-common/lib/common/iff.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/iff'>;
}
declare module 'feathers-hooks-common/lib/common/is-not.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/is-not'>;
}
declare module 'feathers-hooks-common/lib/common/set-by-dot.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/set-by-dot'>;
}
declare module 'feathers-hooks-common/lib/common/some.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/some'>;
}
declare module 'feathers-hooks-common/lib/common/unless.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/common/unless'>;
}
declare module 'feathers-hooks-common/lib/filters/combine.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/filters/combine'>;
}
declare module 'feathers-hooks-common/lib/filters/index.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/filters/index'>;
}
declare module 'feathers-hooks-common/lib/filters/pluck.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/filters/pluck'>;
}
declare module 'feathers-hooks-common/lib/filters/remove.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/filters/remove'>;
}
declare module 'feathers-hooks-common/lib/filters/set-filtered-at.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/filters/set-filtered-at'>;
}
declare module 'feathers-hooks-common/lib/filters/traverse.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/filters/traverse'>;
}
declare module 'feathers-hooks-common/lib/index.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/index'>;
}
declare module 'feathers-hooks-common/lib/permissions/combine.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/permissions/combine'>;
}
declare module 'feathers-hooks-common/lib/permissions/index.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/permissions/index'>;
}
declare module 'feathers-hooks-common/lib/services/callback-to-promise.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/callback-to-promise'>;
}
declare module 'feathers-hooks-common/lib/services/check-context-if.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/check-context-if'>;
}
declare module 'feathers-hooks-common/lib/services/check-context.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/check-context'>;
}
declare module 'feathers-hooks-common/lib/services/client.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/client'>;
}
declare module 'feathers-hooks-common/lib/services/combine.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/combine'>;
}
declare module 'feathers-hooks-common/lib/services/de-populate.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/de-populate'>;
}
declare module 'feathers-hooks-common/lib/services/debug.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/debug'>;
}
declare module 'feathers-hooks-common/lib/services/disable-multi-item-change.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/disable-multi-item-change'>;
}
declare module 'feathers-hooks-common/lib/services/disable.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/disable'>;
}
declare module 'feathers-hooks-common/lib/services/disallow.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/disallow'>;
}
declare module 'feathers-hooks-common/lib/services/discard.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/discard'>;
}
declare module 'feathers-hooks-common/lib/services/get-items.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/get-items'>;
}
declare module 'feathers-hooks-common/lib/services/index.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/index'>;
}
declare module 'feathers-hooks-common/lib/services/is-provider.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/is-provider'>;
}
declare module 'feathers-hooks-common/lib/services/legacy-populate.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/legacy-populate'>;
}
declare module 'feathers-hooks-common/lib/services/lower-case.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/lower-case'>;
}
declare module 'feathers-hooks-common/lib/services/params-for-server.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/params-for-server'>;
}
declare module 'feathers-hooks-common/lib/services/params-from-client.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/params-from-client'>;
}
declare module 'feathers-hooks-common/lib/services/pluck-query.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/pluck-query'>;
}
declare module 'feathers-hooks-common/lib/services/pluck.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/pluck'>;
}
declare module 'feathers-hooks-common/lib/services/populate.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/populate'>;
}
declare module 'feathers-hooks-common/lib/services/prevent-changes.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/prevent-changes'>;
}
declare module 'feathers-hooks-common/lib/services/promise-to-callback.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/promise-to-callback'>;
}
declare module 'feathers-hooks-common/lib/services/remove-query.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/remove-query'>;
}
declare module 'feathers-hooks-common/lib/services/remove.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/remove'>;
}
declare module 'feathers-hooks-common/lib/services/replace-items.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/replace-items'>;
}
declare module 'feathers-hooks-common/lib/services/serialize.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/serialize'>;
}
declare module 'feathers-hooks-common/lib/services/set-created-at.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/set-created-at'>;
}
declare module 'feathers-hooks-common/lib/services/set-now.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/set-now'>;
}
declare module 'feathers-hooks-common/lib/services/set-slug.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/set-slug'>;
}
declare module 'feathers-hooks-common/lib/services/set-updated-at.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/set-updated-at'>;
}
declare module 'feathers-hooks-common/lib/services/sifter.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/sifter'>;
}
declare module 'feathers-hooks-common/lib/services/soft-delete.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/soft-delete'>;
}
declare module 'feathers-hooks-common/lib/services/stash-before.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/stash-before'>;
}
declare module 'feathers-hooks-common/lib/services/traverse.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/traverse'>;
}
declare module 'feathers-hooks-common/lib/services/validate-schema.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/validate-schema'>;
}
declare module 'feathers-hooks-common/lib/services/validate.js' {
  declare module.exports: $Exports<'feathers-hooks-common/lib/services/validate'>;
}
